### ISSUE TITLE
Report benchmarks in original order

### ISSUE THREAD

**Issue by nmattia** [tweag/hyperion#22]
The report generated by `--pretty` shows the benchmarks in (pseudo-) random order.

```
printReports :: HashMap Text Report -> IO ()
printReports report = do
  putDoc $ foldMap formatReport (elems report)
```

`elems` returns the elements using whatever order is used inside the hash map (probably ordered by hashes). It would be great to have the results reported in the order defined in the user code.

**Comment by Fuuzetsu** [comment]
quick search finds https://hackage.haskell.org/package/linkedhashmap-0.4.0.0/docs/Data-LinkedHashMap-Seq.html

**Comment by qnikst** [comment]
Is there benefit of using HashMap there? Do we use random accesses there?

**Comment by mgsloan** [comment]
I just ran into this.  It would also be nice to group or intent the pretty output.

Quite annoying to have to manually edit the text..
