### ISSUE TITLE
Allow to dump raw results into a file.

### ISSUE THREAD

**Issue by qnikst** [tweag/hyperion#6]
Currently all output goes into `stdout`. This way it makes impossible to get raw results without additional output when run with stack. As `stack bench ..` will write it's own output, and `stack bench --silent` hides all output including output of the hyperion.

Proposal:

Change meaning of the `--raw` option and make it `--raw=file.json` in case if it's set -- all output should go into the `file.json` instead. And stdout output should be same as without `--raw` option.

**Comment by gamazeps** [comment]
@qnikst would the PR #12 solve your issue as it allows to dump the raw output in a file, or do you need both the JSON with the raw data and the JSON without the raw data ?

**Comment by qnikst** [comment]
#12  will work, I do not see a usecase for two JSON files.

**Comment by gamazeps** [comment]
Awesome :)

**Comment by gamazeps** [comment]
Solved by #12
